version: '3'

services:
  nginx:
    image: "nginx:alpine"
    depends_on:
      - php
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${SOURCE_DIR}:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - default
    restart: always
    container_name: nginx

  php:
    build: ./php
    ports:
      - "9000"
    volumes:
      - ${SOURCE_DIR}:/var/www
      - ./php/config:/usr/local/etc/php
    networks:
      - default
    restart: always
    links:
      - mysql:mysql
      - redis:redis
    container_name: php

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - ${REDIS_DATA_DIR}:/data:rw
    restart: always
    networks:
      - default
    container_name: redis

  mysql:
    image: "mariadb:10.1.38"
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d:ro
      - ${MYSQL_DATA_DIR}:/var/lib/mysql:rw
    environment:
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
    restart: always
    networks:
      - default
    container_name: mysql

  pma:
    image: "phpmyadmin/phpmyadmin"
    ports:
      - "8080:80"
    restart: always
    container_name: pma
    links:
      - mysql:db

  adminer:
    image: "adminer"
    ports:
      - "8000:8080"
    restart: always
    container_name: adminer
    links:
      - mysql:db

