version: '3'

services:
  nginx:
    image: "nginx:latest"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /Users/yinyanjun/codes:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - default
    restart: always
    container_name: nginx

  #mysql:
  #  build: ./mysql

  #php:
  #  build: ./php
