version: '3'

networks:
  phpenv:
    driver: bridge
    ipam: 
      config: 
        - subnet: 168.18.0.0/24

services:
  nginx:
    image: "nginx:alpine"
    depends_on:
      - php
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${SOURCE_DIR}:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      phpenv:
        ipv4_address: 168.18.0.10
    restart: always
    container_name: nginx

  php:
    build: ./php
    ports:
      - "9000"
    volumes:
      - ${SOURCE_DIR}:/var/www:cached
      - ./php/config:/usr/local/etc/php
    networks:
      phpenv:
        ipv4_address: 168.18.0.11
    restart: always
    extra_hosts:
      - sso.tianyisoft.com:168.18.0.10
      - api.tianyisoft.com:168.18.0.10
    container_name: php

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - ${REDIS_DATA_DIR}:/data:rw
    restart: always
    networks:
      phpenv:
        ipv4_address: 168.18.0.12
    container_name: redis


  mysql57:
    image: "mysql:5"
    ports: 
      - "3307:3306"
    volumes:
      - ./mysql57/conf.d:/etc/mysql/conf.d:ro
      - ${MYSQL57_DATA_DIR}:/var/lib/mysql:rw
    environment:
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
    restart: always
    networks:
      phpenv:
        ipv4_address: 168.18.0.13
    container_name: mysql57

  mongodb:
    image: "mongo:latest"
    volumes:
      - ./mongodb/db:/data/db
    restart: always
    networks:
      phpenv:
        ipv4_address: 168.18.0.14
    container_name: mongodb


  adminer:
    image: "adminer"
    ports:
      - "8000:8080"
    restart: always
    container_name: adminer
    networks:
      phpenv:
        ipv4_address: 168.18.0.15
    links:
      - mysql:db
      - mysql57

  sso:
    image: "sso:v1"
    volumes:
      - /Users/yinyanjun/codes/sso:/app
    restart: always
    networks:
      phpenv:
        ipv4_address: 168.18.0.16
    extra_hosts:
      - cfs.tianyisoft.com:168.18.0.10
    container_name: sso


  mysql:
    image: "mariadb:10.1.38"
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d:ro
      - ${MYSQL_DATA_DIR}:/var/lib/mysql:rw
    environment:
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
    restart: always
    networks:
      phpenv:
        ipv4_address: 168.18.0.17
    container_name: mysql